### PR TITLE
Fix task without resources locking resources

### LINKED ISSUE #214: Tasks are locked even though it has no resources
I have a test case which doesn't require any locks. When running it repeatedly the runner marks it as locked regardless of wether it has resources or not. This happens because we added a dummy lock here:

https://github.com/boxine/pentf/blob/2030a4a86192b03364a964735372cff4ce7610cc/locking.js#L23-L25

### PR DESCRIPTION
**Pull request by marvinhagemeister**
Fixes #214 .

### CODE REVIEW

File: locking.js [hunk 1]
```diff
@@ -14,14 +14,8 @@ function annotateTaskResources(config, task) {
         return;
     }
 
-    const {tc} = task;
```
Comment (phihag) [inline locking.js:17]: Don't we need to copy `task.resources = tc.resources`?

File: locking.js [hunk 2]
```diff
@@ -60,7 +54,6 @@ async function acquire(config, state, task) {
     if (config.no_locking) return true;
 
     assert(task);
-    assert(task.resources);
```
Comment (phihag) [inline locking.js:63]: Why can this assertion be removed, but the following can't?

Comment (marvinhagemeister) [reply locking.js:63]: With this PR `task.resources` will always be an array. If it is empty we can bail out early. Otherwise we'd run the `external_locking.externalAcquire()` branch a few lines below.

File: tests/selftest_no_locks.js [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+            run() {},
+        },
+        {
+            name: 'B',
+            run() {},
+        },
+    ];
+    await runner.run(
+        {
+            quite: true,
```
Comment (jzaefferer) [inline tests/selftest_no_locks.js:16]: Is this a typo? I guess it should be `quiet: true`.
